routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return redirect('/login'); });

 Route::get('/home', function () { return redirect()->route('home'); });


Route::group(['middleware' => ['web','auth','permission:access_panel'], 'prefix' => 'panel'], function () {

    Route::group(['middleware' => ['permission:access_admin'], 'prefix' => 'admin'], function () { 

            Route::get('home', 'AdminController@index')->name('admin.index');

    });


    Route::get('ajax/setup-alert', 'SiteController@setupAlert')->name('setupAlert');



    /*ORGANIZATION ROUTES*/

    Route::get('ajax/organization/OrganizationWithID', 'OrganizationController@OrganizationWithID')->name('OrganizationWithID');
    Route::post('ajax/organization/setOrganization', 'OrganizationController@setOrganizationViaAjax')->name('setOrganizationViaAjax');
    Route::get('organization/select', 'OrganizationController@select')->name('OrgSelect');    
 

    /*PROJECT ROUTES*/
  
    Route::get('project/select', 'ProjectController@select')->name('ProjectSelect');
    Route::get('ajax/project/ProjectWithID', 'ProjectController@ProjectWithID')->name('ProjectWithID');
    Route::post('ajax/project/setProject', 'ProjectController@setProjectViaAjax')->name('setProjectViaAjax');
    Route::get('ajax/stage/department', 'StageController@listByDepartment')->name('StageByDepartment');
    Route::get('ajax/stage/rate', 'StageController@standardRate')->name('StageStandardRate');

    Route::group(['middleware' => ['OrgProjectIfSet']],function () {
            
            /*ITEMS ROUTES*/
            Route::post('ajax/item/incharge', 'ItemController@itemIncharge')->name('itemIncharge');

            /*SUPPLIER AJAX*/

            Route::get('ajax/supplier/items', 'ItemController@supplierItems')->name('supplierItems');
            Route::get('ajax/supplier/balance', 'SupplierController@balance')->name('supplier-balance');
            Route::post('ajax/supplier/remove-item', 'ItemController@RemoveSupplierItem')->name('supplier-item-remove');
            Route::get('ajax/supplier/grn/unpaid', 'OrderGrnController@supplierGrn')->name('supplier-grn-unpaid');

            /*CONTRACTOR*/

            Route::get('ajax/contractor/department', 'ContractorController@listByDepartment')->name('ContractorByDepartment');
            Route::get('ajax/contractor/balance', 'ContractorController@balance')->name('contractor-balance');
            Route::get('ajax/contractor/unpaid-task', 'ContractorController@unpaidTask')->name('contractor-unpaid-task');

            /*OTHER ROUTES*/
            Route::get('home', 'SiteController@index')->name('home');



            /*PROJECT ROUTES*/
            Route::group(['prefix' => 'project'], function () {

                
                Route::get('product-property/list', 'ProductPropertyController@listProductProperties')->name('ProjectPropertyList');
                Route::get('product-category/list', 'ProductCategoryController@getProductCategoriesviaAjax')->name('ProductCategoriesviaAjax');
                Route::get('product-category/manage/{id}', 'ProductCategoryController@show')->name('ShowProductCategory');
                Route::post('product-category/assign', 'ProductCategoryController@assignPropertyHeader')->name('assignPropertyHeader');
                Route::post('add-product-catrgory-product', 'ProductCategoryController@AddProdToCategory')->name('AddProdToCategory');
                Route::post('delete-product-catrgory-product', 'ProductCategoryController@DeleteProdFromCategory')->name('DeleteProdFromCategory');

                Route::post('product/action', 'ProductController@action')->name('product-action');

               
                Route::resource('project-managers','ProjectManagerController');
                Route::resource('product','ProductController');
                Route::resource('product-category','ProductCategoryController');
                Route::resource('product-property/header','ProductPropertyHeaderController');
                Route::resource('product-property','ProductPropertyController');
                Route::resource('product-items','ProductItemController');
               

            });

            Route::get('order/view/{order}', 'OrderController@show')->name('view-order');
            Route::get('order/grn/prepare/{Orderid}', 'OrderController@prepareGrn')->name('prepare-grn');

            Route::get('user/login/logs','LoginLogsController@logs')->name('login-logs');
            Route::get('user/exists','UserController@checkUser')->name('user-exists');

            Route::get('inventory/items','InventoryController@items')->name('inventory-items');
            


            Route::post('payments/pay','PaymentController@pay')->name('payments-pay');

            Route::get('payments/transaction','PaymentController@viewTransaction')->name('payments-transaction');

            Route::get('payments/transaction/bank/{id}','PaymentController@bankTransaction')->name('bank-transaction');

            Route::get('payments/material-payment/create','PaymentController@materialPayment')->name('material-payment');
            Route::get('payments/contractor-payment/create','PaymentController@contractorPayment')->name('contractor-payment');
            Route::get('payments/service-payment/create','PaymentController@servicePayment')->name('service-payment');
            Route::get('payments/external-payment/create','PaymentController@externalPayment')->name('external-payment');
            Route::get('payments/external-income/create','PaymentController@externalIncome')->name('external-income');
            Route::get('payments/customer-payment/create','PaymentController@customerPayment')->name('customer-payment');

            Route::get('payments/view/{paymentid}','PaymentController@show')->name('show-payment');

            Route::get('payments/receipt/{paymentid}','PaymentController@receipt')->name('receipt');
            Route::get('payments/voucher/{paymentid}','PaymentController@voucher')->name('voucher');

            Route::any('bank-accounts/ajax','BankAccountController@ajax')->name('banks-ajax');
            Route::any('order/ajax','OrderController@ajax')->name('order-ajax');

            Route::post('change-request/update','ChangeRequestController@updateChangeRequest')->name('update-cr');
            
            Route::any('customer/products','ProductCustomerController@customerProductsCombo')->name('customer-products-combo');
            Route::any('product/cost','ProductController@cost')->name('product-cost');
            Route::any('product/upgrades','ProductController@upgrades')->name('product-upgrades');

            Route::get('reports','ReportController@index')->name('reports');
            Route::any('reports/generate','ReportController@generate')->name('report-generate');


            Route::resource('order','OrderController');
            Route::resource('ordergrn','OrderGrnController');
            Route::resource('supplier','SupplierController');
            Route::resource('contractor','ContractorController');
            Route::resource('department','DepartmentController');
            Route::resource('item','ItemController');
            Route::resource('tax','TaxController');
            Route::resource('staff','StaffController');
            Route::resource('stages','StageController');
            Route::resource('product-stages','ProductStageController');
            Route::resource('customer','CustomerController');
            Route::resource('material-transfer','MaterialTransferController');
            Route::resource('inventory','InventoryController');
            Route::resource('bank-accounts','BankAccountController');
            Route::resource('payments','PaymentController');
            Route::resource('product-customer','ProductCustomerController');
            Route::resource('change-request','ChangeRequestController');

    });

     Route::resource('organization','OrganizationController');
     Route::resource('project','ProjectController');
    


    
});

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Validator;

use Auth;

use Session;

use App\Supplier;

use App\Department;

use App\Item;
use App\ItemDepartment;
use App\ItemStaff;
use App\ItemSupplier;
use App\Tax;
use App\Staff;

class ItemController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Items = Item::ofOrg()->get();

        return view('item.list',['Items'=>$Items]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $indiaStates = getIndiaStates();

        $Suppliers = Supplier::ofOrg()->orderBy('name','asc')->get()->pluck('name','id');

        $Departments = Department::ofOrg()->get()->pluck('name','id');

        $Tax = Tax::ofOrg()->get()->pluck('fullname','id');

        $Staff = Staff::fromOrg()->pluck('fullname','id');
  
        return view('item.add',['indiaStates'=>$indiaStates, 'suppliers'=>$Suppliers, 'departments'=>$Departments,'tax'=>$Tax,'staff'=>$Staff]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [

            'code' => 'required',
            'name' => 'required',
            'supplier' => 'required',
            'unit' => 'required',
            'unit_price' => 'required',
            'tax' => 'required',
            'departments' => 'required'

        ]);

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $project_id = getProject('proj_id');
        $org_id = getOrganization('org_id');

        $Item = new Item();

        $Item->org_id = $org_id;
        $Item->project_id = $project_id;
        $Item->tax_id = $request->input('tax');
        $Item->code = $request->input('code');
        $Item->name = $request->input('name');
        $Item->description = $request->input('description');
        $Item->unit = $request->input('unit');
        $Item->unit_price = $request->input('unit_price');
        $Item->discount = $request->input('discount');
        $Item->roq = $request->input('roq');
    
        $Item->save();

        $ItemID = $Item->id;

        /*Add Suppliers to Items*/

         foreach ($request->input('supplier') as $supplier) {
            $itemSuppl[] = array('item_id'=>$ItemID, 'supplier_id'=>$supplier);
        }

        $ItemSupplier = ItemSupplier::insert($itemSuppl);

        /*Add Item to Departments*/

        foreach ($request->input('departments') as $department_id) {
            $itemDept[] = array('project_id'=>$project_id, 'org_id'=>$org_id,'item_id'=>$ItemID, 'department_id'=>$department_id);
        }

        $ItemDepartment = ItemDepartment::insert($itemDept);


        /*Add Contact to Departments*/
        if(!empty($request->input('staff') ))
        {
             foreach ($request->input('staff') as $staff) {
                $itemStaff[] = array('staff_id'=>$staff, 'item_id'=>$ItemID);
            }

             ItemStaff::insert($itemStaff);
            
        }

         return redirect()->route('item.index','created=true');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Item = Item::find($id);

        $project_id = $Item->project_id;

        $org_id = $Item->org_id;

        $indiaStates = getIndiaStates();

        $Suppliers = Supplier::ofOrg()->orderBy('name','asc')->get()->pluck('name','id');

        $ItemSupplier = $Item->suppliers->pluck('supplier_id')->toArray();

        $Departments = Department::ofOrg()->get()->pluck('name','id');

        $ItemDepartment = $Item->departments->pluck('department_id')->toArray();

        $Tax = Tax::ofOrg()->get()->pluck('fullname','id');

        $Staff = Staff::fromOrg()->pluck('fullname','id');

        $ItemStaff = $Item->staff->pluck('staff_id')->toArray();

        return view('item.edit',['indiaStates'=>$indiaStates, 'suppliers'=>$Suppliers, 'departments'=>$Departments,'tax'=>$Tax,'item'=>$Item,'ItemSupplier'=>$ItemSupplier,'ItemDepartment'=>$ItemDepartment,'staff'=>$Staff, 'ItemStaff'=> $ItemStaff]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [

            'code' => 'required',
            'name' => 'required',
            'supplier' => 'required',
            'unit' => 'required',
            'unit_price' => 'required',
            'tax' => 'required',
            'departments' => 'required'

        ]);

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $Item = Item::findOrFail($id);

        $Item->tax_id = $request->input('tax');
        $Item->code = $request->input('code');
        $Item->name = $request->input('name');
        $Item->description = $request->input('description');
        $Item->unit = $request->input('unit');
        $Item->unit_price = $request->input('unit_price');
        $Item->discount = $request->input('discount');
        $Item->roq = $request->input('roq');
        
        $Item->save();

        $ItemID = $id;

        /*Add Suppliers to Items*/

        foreach ($request->input('supplier') as $supplier) {
            $itemSuppl[] = array('item_id'=>$ItemID, 'supplier_id'=>$supplier);
        }

        ItemSupplier::where('item_id',$ItemID)->delete();

        $ItemSupplier = ItemSupplier::insert($itemSuppl);

        /*Add Departments*/

        foreach ($request->input('departments') as $department_id) {
            $itemDept[] = array('project_id'=>$Item->project_id, 'org_id'=>$Item->org_id,'item_id'=>$ItemID, 'department_id'=>$department_id);
        }

        ItemDepartment::where('item_id',$ItemID)->delete();
        $ItemDepartment = ItemDepartment::insert($itemDept);


        /*Add Staff*/
        
        ItemStaff::where('item_id',$ItemID)->delete();

        if(sizeof($request->input('staff')) > 0)
        {
            foreach ($request->input('staff') as $staff) {
                $itemStaff[] = array('staff_id'=>$staff, 'item_id'=>$ItemID);
            }
            
            ItemStaff::insert($itemStaff);
        }

        

         return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Item::destroy($id);
        ItemSupplier::where('item_id',$id)->delete();

        return redirect()->back();
    }

    public function itemIncharge(Request $request)
    {
        $item_id = $request->input('id');

        $ItemContacts = ItemStaff::where('item_id',$item_id)->get();

        return view('item.incharge', ['incharges'=>$ItemContacts]);
    }

    public function supplierItems($supplierid="",Request $request)
    {
        $supplierid = ($supplierid != "" ? $supplierid : $request->input('supplier_id'));

        if($supplierid > 0)
        {
            $ItemSuppliers = ItemSupplier::where('supplier_id',$supplierid)->get();

            foreach ($ItemSuppliers as $row) {
                @$items[] = array("item_id"=>$row->item->id,"item_name"=>$row->item->name,"item_code"=>$row->item->code,"item_unit"=>$row->item->unit,"item_unit_price"=>$row->item->unit_price,"item_discount"=>$row->item->discount, "tax_name"=>$row->item->tax->name, "tax"=>$row->item->tax->percent, "roq"=>$row->item->roq);
            }
         
            $Supplier = Supplier::find($supplierid);

            if( $request->input('table') == true)
                return view('item.suppliersItem',['items'=>$items,'Supplier'=>$Supplier]);
            else
                return $items;
        }
    }

    public function RemoveSupplierItem(Request $request)
    {
        $supplier_id = $request->input('supplier_id');
        $item_id = $request->input('item_id');

        ItemSupplier::where('item_id',$item_id)->where('supplier_id',$supplier_id)->delete();

    }

}

resources/views/item/add.blade.php
@extends('master')

@section('title','Add New Item')

@section('pagecontent')

  <div class="ks-column ks-page">

        <div class="ks-header">
            <section class="ks-title">
                <h3>Add New Item</h3>
                <button type="button" onclick="$('#item_add_frm').submit()" class="btn btn-success pull-right">Add</button>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						
						@include('common.pagetop')

						{{ Form::open(['action' => 'ItemController@store', 'id'=>'item_add_frm']) }}
						
						<div class="row">
							<div class="col-lg-12">

							<div class="card">
		                        <div class="card-block">
		                            <h5 class="card-title">Item's Primary Details</h5>
		                         		
		                         		<div class="form-group row">
		                                    <label for="code" class="col-sm-4 form-control-label">Select Suppliers</label>
		                                    <div class="col-sm-8">
												  	{{ Form::select('supplier[]', $suppliers, null, ['class'=>'form-control', 'multiple']) }}
		                                    </div>
		                                </div>
		                            	
		                            	<div class="form-group row">
		                                    <label for="code" class="col-sm-4 form-control-label">Item Code</label>
		                                    <div class="col-sm-8">
												{{ Form::text('code', '',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="name" class="col-sm-4 form-control-label">Item Name</label>
		                                    <div class="col-sm-8">
												{{ Form::text('name','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>
										
										<div class="form-group row">
		                                    <label for="description" class="col-sm-4 form-control-label">Item Description</label>
		                                    <div class="col-sm-8">
												{{ Form::text('description','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                
		                                <div class="form-group row">
		                                    <label for="unit" class="col-sm-4 form-control-label">Item Unit</label>
		                                    <div class="col-sm-8">
												{{ Form::text('unit','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                 <div class="form-group row">
		                                    <label for="unit_price" class="col-sm-4 form-control-label">Item Unit Price</label>
		                                    <div class="col-sm-8">
												{{ Form::number('unit_price','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="discount" class="col-sm-4 form-control-label">Item Discount %</label>
		                                    <div class="col-sm-8">
												{{ Form::number('discount',0,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                 <div class="form-group row">
		                                    <label for="item_state" class="col-sm-4 form-control-label">Select Tax</label>
		                                    <div class="col-sm-8">
		                                       	{{ Form::select('tax', $tax, null , ['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="roq" class="col-sm-4 form-control-label">Item ROQ</label>
		                                    <div class="col-sm-8">
												{{ Form::text('roq','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="item_state" class="col-sm-4 form-control-label">Select Departments</label>
		                                    <div class="col-sm-8">
		                                       	{{ Form::select('departments[]', $departments, (isset($_GET['dep']) ? $_GET['dep'] : null) , ['class'=>'form-control', 'multiple']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="item_state" class="col-sm-4 form-control-label">Assign Staff</label>
		                                    <div class="col-sm-8">
		                                       	{{ Form::select('staff[]', $staff, null , ['class'=>'form-control', 'multiple']) }}
		                                    </div>
		                                </div>

		                              


		                        </div>
		                    </div>

		                    <!-- END Item NAME BLOCK -->

							
			            </div>

			            <div class="col-lg-6"></div>

						</div>
						{{ Form::close() }}
					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection

resources/views/item/edit.blade.php
@extends('master')

@section('title','Edit Item')

@section('pagecontent')

  <div class="ks-column ks-page">

        <div class="ks-header">
            <section class="ks-title">
                <h3>Edit Item: <small>{{ $item->name }}</small></h3>
                <button type="button" onclick="$('#item_add_frm').submit()" class="btn btn-success pull-right">Update</button>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						
						@include('common.pagetop')

						{{ Form::open(['method'=>'PUT','action' => ['ItemController@update',$item->id], 'id'=>'item_add_frm']) }}
						
						<div class="row">
							<div class="col-lg-6">

							<div class="card">
		                        <div class="card-block">
		                            <h5 class="card-title">Item's Primary Details</h5>
		                         		
		                         		<div class="form-group row">
		                                    <label for="code" class="col-sm-4 form-control-label">Select Suppliers</label>
		                                    <div class="col-sm-8">
												  	{{ Form::select('supplier[]', $suppliers, $ItemSupplier, ['class'=>'form-control', 'multiple']) }}
		                                    </div>
		                                </div>
		                            	
		                            	<div class="form-group row">
		                                    <label for="code" class="col-sm-4 form-control-label">Item Code</label>
		                                    <div class="col-sm-8">
												{{ Form::text('code', $item->code,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="name" class="col-sm-4 form-control-label">Item Name</label>
		                                    <div class="col-sm-8">
												{{ Form::text('name', $item->name,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="description" class="col-sm-4 form-control-label">Item Description</label>
		                                    <div class="col-sm-8">
												{{ Form::text('description', $item->description,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                 <div class="form-group row">
		                                    <label for="unit" class="col-sm-4 form-control-label">Item Unit</label>
		                                    <div class="col-sm-8">
												{{ Form::text('unit', $item->unit,['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                  <div class="form-group row">
		                                    <label for="unit" class="col-sm-4 form-control-label">Item Unit Price</label>
		                                    <div class="col-sm-8">
												{{ Form::number('unit_price', $item->unit_price,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="unit" class="col-sm-4 form-control-label">Item Discount %</label>
		                                    <div class="col-sm-8">
												{{ Form::number('discount',$item->discount,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                 <div class="form-group row">
		                                    <label for="item_state" class="col-sm-4 form-control-label">Select Tax</label>
		                                    <div class="col-sm-8">
		                                       	{{ Form::select('tax', $tax, $item->tax_id , ['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="roq" class="col-sm-4 form-control-label">Item ROQ</label>
		                                    <div class="col-sm-8">
												{{ Form::text('roq',$item->roq,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="item_state" class="col-sm-4 form-control-label">Select Departments</label>
		                                    <div class="col-sm-8">
		                                       	{{ Form::select('departments[]', $departments, $ItemDepartment , ['class'=>'form-control', 'multiple']) }}
		                                    </div>
		                                </div>

										 <div class="form-group row">
		                                    <label for="item_state" class="col-sm-4 form-control-label">Assign Staff</label>
		                                    <div class="col-sm-8">
		                                      {{ Form::select('staff[]', $staff, $ItemStaff , ['class'=>'form-control', 'multiple']) }}
		                                    </div>
		                                </div>
		                              


		                        </div>
		                    </div>

		                    <!-- END Item NAME BLOCK -->

							
			            </div>

			            
						</div>
						{{ Form::close() }}
					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection

resources/views/item/list.blade.php
@extends('master')

@section('title','List Project Items')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">

                <h3>List Items: <small>{{ getOrganization('org_name') }}</small></h3>
              <a href="{{ URL::Action('ItemController@create') }}"  class="btn btn-success pull-right">Add New</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						
						<div class="card">
		                        <div class="card-block">
		                            <h5 class="card-title">You have {{ $Items->count() }} items added to this organization</h5>
									
									@if($Items->count() > 0)

										<table class="table datatable">
											<thead>
												<tr>
													<th>Item Code</th>
													<th>Item Name</th>
													<th>Units</th>
													<th>Suppliers</th>
													<th>Tax</th>
													<th>Manage</th>
												</tr>
											</thead>

											<tbody>
												@foreach($Items as $Item)
													<tr>
														<td><strong>{{ $Item->code }}</strong></td>
														<td><strong>{{ $Item->name }}</strong></td>
														<td>{{ $Item->unit }}</td>
														<td>
															@foreach($Item->suppliers as $row)

																<a  target="_blank"  class="link" href="{{ route('supplier.show',$row->supplier->id) }}">{{ $row->supplier->name }}</a>

															@endforeach
														</td>
														<td>{{ @$Item->tax->fullname }}</td>
														<td>{!! deleteEditModelBtn("item",$Item->id, $Item->name) !!}</td>
													</tr>
												@endforeach
											</tbody>

										</table>

									@else
										Please add atleast One item to project
									@endif
		                        </div>
		                </div>

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection