routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return redirect('/login'); });

 Route::get('/home', function () { return redirect()->route('home'); });


Route::group(['middleware' => ['web','auth','permission:access_panel'], 'prefix' => 'panel'], function () {

    Route::group(['middleware' => ['permission:access_admin'], 'prefix' => 'admin'], function () { 

            Route::get('home', 'AdminController@index')->name('admin.index');

    });


    Route::get('ajax/setup-alert', 'SiteController@setupAlert')->name('setupAlert');



    /*ORGANIZATION ROUTES*/

    Route::get('ajax/organization/OrganizationWithID', 'OrganizationController@OrganizationWithID')->name('OrganizationWithID');
    Route::post('ajax/organization/setOrganization', 'OrganizationController@setOrganizationViaAjax')->name('setOrganizationViaAjax');
    Route::get('organization/select', 'OrganizationController@select')->name('OrgSelect');    
 

    /*PROJECT ROUTES*/
  
    Route::get('project/select', 'ProjectController@select')->name('ProjectSelect');
    Route::get('ajax/project/ProjectWithID', 'ProjectController@ProjectWithID')->name('ProjectWithID');
    Route::post('ajax/project/setProject', 'ProjectController@setProjectViaAjax')->name('setProjectViaAjax');
    Route::get('ajax/stage/department', 'StageController@listByDepartment')->name('StageByDepartment');
    Route::get('ajax/stage/rate', 'StageController@standardRate')->name('StageStandardRate');

    Route::group(['middleware' => ['OrgProjectIfSet']],function () {
            
            /*ITEMS ROUTES*/
            Route::post('ajax/item/incharge', 'ItemController@itemIncharge')->name('itemIncharge');

            /*SUPPLIER AJAX*/

            Route::get('ajax/supplier/items', 'ItemController@supplierItems')->name('supplierItems');
            Route::get('ajax/supplier/balance', 'SupplierController@balance')->name('supplier-balance');
            Route::post('ajax/supplier/remove-item', 'ItemController@RemoveSupplierItem')->name('supplier-item-remove');
            Route::get('ajax/supplier/grn/unpaid', 'OrderGrnController@supplierGrn')->name('supplier-grn-unpaid');

            /*CONTRACTOR*/

            Route::get('ajax/contractor/department', 'ContractorController@listByDepartment')->name('ContractorByDepartment');
            Route::get('ajax/contractor/balance', 'ContractorController@balance')->name('contractor-balance');
            Route::get('ajax/contractor/unpaid-task', 'ContractorController@unpaidTask')->name('contractor-unpaid-task');

            /*OTHER ROUTES*/
            Route::get('home', 'SiteController@index')->name('home');



            /*PROJECT ROUTES*/
            Route::group(['prefix' => 'project'], function () {

                
                Route::get('product-property/list', 'ProductPropertyController@listProductProperties')->name('ProjectPropertyList');
                Route::get('product-category/list', 'ProductCategoryController@getProductCategoriesviaAjax')->name('ProductCategoriesviaAjax');
                Route::get('product-category/manage/{id}', 'ProductCategoryController@show')->name('ShowProductCategory');
                Route::post('product-category/assign', 'ProductCategoryController@assignPropertyHeader')->name('assignPropertyHeader');
                Route::post('add-product-catrgory-product', 'ProductCategoryController@AddProdToCategory')->name('AddProdToCategory');
                Route::post('delete-product-catrgory-product', 'ProductCategoryController@DeleteProdFromCategory')->name('DeleteProdFromCategory');

                Route::post('product/action', 'ProductController@action')->name('product-action');

               
                Route::resource('project-managers','ProjectManagerController');
                Route::resource('product','ProductController');
                Route::resource('product-category','ProductCategoryController');
                Route::resource('product-property/header','ProductPropertyHeaderController');
                Route::resource('product-property','ProductPropertyController');
                Route::resource('product-items','ProductItemController');
               

            });

            Route::get('order/view/{order}', 'OrderController@show')->name('view-order');
            Route::get('order/grn/prepare/{Orderid}', 'OrderController@prepareGrn')->name('prepare-grn');

            Route::get('user/login/logs','LoginLogsController@logs')->name('login-logs');
            Route::get('user/exists','UserController@checkUser')->name('user-exists');

            Route::get('inventory/items','InventoryController@items')->name('inventory-items');
            


            Route::post('payments/pay','PaymentController@pay')->name('payments-pay');

            Route::get('payments/transaction','PaymentController@viewTransaction')->name('payments-transaction');

            Route::get('payments/transaction/bank/{id}','PaymentController@bankTransaction')->name('bank-transaction');

            Route::get('payments/material-payment/create','PaymentController@materialPayment')->name('material-payment');
            Route::get('payments/contractor-payment/create','PaymentController@contractorPayment')->name('contractor-payment');
            Route::get('payments/service-payment/create','PaymentController@servicePayment')->name('service-payment');
            Route::get('payments/external-payment/create','PaymentController@externalPayment')->name('external-payment');
            Route::get('payments/external-income/create','PaymentController@externalIncome')->name('external-income');
            Route::get('payments/customer-payment/create','PaymentController@customerPayment')->name('customer-payment');

            Route::get('payments/view/{paymentid}','PaymentController@show')->name('show-payment');

            Route::get('payments/receipt/{paymentid}','PaymentController@receipt')->name('receipt');
            Route::get('payments/voucher/{paymentid}','PaymentController@voucher')->name('voucher');

            Route::any('bank-accounts/ajax','BankAccountController@ajax')->name('banks-ajax');
            Route::any('order/ajax','OrderController@ajax')->name('order-ajax');

            Route::post('change-request/update','ChangeRequestController@updateChangeRequest')->name('update-cr');
            
            Route::any('customer/products','ProductCustomerController@customerProductsCombo')->name('customer-products-combo');
            Route::any('product/cost','ProductController@cost')->name('product-cost');
            Route::any('product/upgrades','ProductController@upgrades')->name('product-upgrades');

            Route::get('reports','ReportController@index')->name('reports');
            Route::any('reports/generate','ReportController@generate')->name('report-generate');


            Route::resource('order','OrderController');
            Route::resource('ordergrn','OrderGrnController');
            Route::resource('supplier','SupplierController');
            Route::resource('contractor','ContractorController');
            Route::resource('department','DepartmentController');
            Route::resource('item','ItemController');
            Route::resource('tax','TaxController');
            Route::resource('staff','StaffController');
            Route::resource('stages','StageController');
            Route::resource('product-stages','ProductStageController');
            Route::resource('customer','CustomerController');
            Route::resource('material-transfer','MaterialTransferController');
            Route::resource('inventory','InventoryController');
            Route::resource('bank-accounts','BankAccountController');
            Route::resource('payments','PaymentController');
            Route::resource('product-customer','ProductCustomerController');
            Route::resource('change-request','ChangeRequestController');

    });

     Route::resource('organization','OrganizationController');
     Route::resource('project','ProjectController');
    


    
});

resources/views/home.blade.php
@extends('master')

@section('title','Dashboard')

@section('pagecontent')


@if(isset($project))

    <div class="ks-column ks-page">
        <div class="ks-header">
            <section class="ks-title">
                <h3>Projects Dashboard</h3>
            </section>
        </div>

        <div class="ks-content">
            <div class="ks-body ks-projects-dashboard-page">
                
                <div class="ks-body">

                    <div class="row">
                        <div class="col-md-12"><div class="setup-alert"></div></div>
                    </div>
                    


        <div class="container-fluid ks-rows-section">

            <div class="row ks-widgets-collection">

                <div class="col-lg-3">
                    <div class="ks-dashboard-widget ks-widget-amount-statistics ks-default">
                        <div class="ks-statistics">
                            <span class="ks-amount" data-count-up="{{ $project->orders->count() }}">0</span>
                            <span class="ks-text">Customers</span>
                        </div>                       
                    </div>
                </div>
                
                <div class="col-lg-3">
                    <div class="ks-dashboard-widget ks-widget-amount-statistics ks-default">
                        <div class="ks-statistics">
                            <span class="ks-amount" data-count-up="{{ $project->products->count() }}">0</span>
                            <span class="ks-text">Total Products</span>
                        </div>
                    </div>
                </div>
      

                 
                  <div class="col-lg-3">
                    <div class="ks-dashboard-widget ks-widget-amount-statistics ks-default">
                        <div class="ks-statistics">
                            <span class="ks-amount" data-count-up="{{ $project->products->where('payment_id', null)->count() }}">0</span>
                            <span class="ks-text">Product Available</span>
                        </div>
                        
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="ks-dashboard-widget ks-widget-amount-statistics ks-default">
                        <div class="ks-statistics">
                            <span class="ks-amount" data-count-up="{{ $project->products->where('payment_id', '>', '0')->count() }}">0</span>
                            <span class="ks-text">Product Sold</span>
                        </div>
                        
                    </div>
                </div>
             
            </div>
            
            <div class="row ks-widgets-collection">
                
                <div class="col-lg-6">
                    <div id="ks-line-chart-panel" class="card panel">
                        <h5 class="card-header">
                            Products Available

                        </h5>
                        <div class="card-block ">
                        <div class="ks-statistics row">
                            

                            @if($project->productcategories->count() > 0)

                               @foreach($project->productcategories as $ProductCategory)

                               <div class="ks-item col-sm-4">
                                <div class="ks-amount">{{ $ProductCategory->products->count() }}</div>
                                <div class="ks-text">{{ $ProductCategory->product_category_name }}</div>
                            </div>

                                
                               @endforeach

                            @else
                                No Product Categories Available! &nbsp;&nbsp; <a href="{{ route('product-category.create') }}">Create Product Category</a>
                            @endif            
                          
                        </div>
                        </div>
                    </div>

                       <div id="ks-bar-chart-panel" class="card panel">
                        <h5 class="card-header">
                            Recent Orders
                        </h5>
                        <div class="card-block">
                           @if($project->orders->count() > 0)

                                        <table class="table table-condensed table=bordered table-hover">
                                            <thead>
                                                <tr>
                                                    
                                                    <th>Order Code</th>
                                                    <th>Invoice Total</th>
                                                    <th>Created On</th>
                                                    <th>Manage</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                @foreach($project->orders->sortByDesc('id')->take(5) as $Order)
                                                    <tr>
                                                        <td><strong>{{ $Order->code }}</strong></td>
                                                        <td>{{ $Order->invoice_total }}</td>
                                                        <td>{{ $Order->created_at }}</td>
                                                        <td><a href="{{ URL::action('OrderController@show',$Order->code) }}" class="btn btn-sm btn-primary" target="_blank">View</a></td>
                                                    </tr>
                                                @endforeach
                                            </tbody>

                                        </table>

                                    @else
                                        No orders yet!
                                    @endif
                        </div>
                    </div>
                </div>


         

                <div class="col-lg-6">


                    <div id="ks-line-chart-panel" class="card panel">
                        <h5 class="card-header">
                            Project Details

                        </h5>
                        <div class="card-block">
                           
                                        <div class="ks-text-block">
                                        <dt>Project Name:</dt>
                                        <dd>{{ $project->proj_code }} - {{ $project->proj_name }}</dd>
                                     
                                        <dt>Address:</dt>
                                        <dd>{{ $project->address_one }}</dd>
                                        <dd>{{ $project->address_two }}</dd>
                                            
                                        <dt>City:</dt>
                                        <dd>{{ $project->city }}</dd>

                                        <dt>State:</dt>
                                        <dd>{{ $project->state }}</dd>

                                        <dt>Pin Code:</dt>
                                        <dd>{{ $project->pincode }}</dd>


                                        </div>
                                
                                    
                        </div>
                    </div>
                

                 
                </div>
                   <div class="col-lg-6">
                       
                   </div>
            </div>
            <div class="row ks-widgets-collection">
                
                    

            </div>

          
        </div>
    
                </div>
            </div>
        </div>
    </div>

    @endif

@endsection

resources/views/master.blade.php
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>@yield('title')</title>



    <meta http-equiv="X-UA-Compatible" content=="IE=edge"/>

    <meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="csrf-token" content="{{ csrf_token() }}">

    <base href="{{ URL('/') }}/">



    <link rel="stylesheet" type="text/css" href="libs/bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="libs/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="assets/fonts/open-sans/styles.css">

    <link rel="stylesheet" type="text/css" href="libs/tether/css/tether.min.css">

    <link rel="stylesheet" type="text/css" href="assets/styles/common.min.css">

     <link rel="stylesheet" type="text/css" href="libs/jscrollpane/jquery.jscrollpane.css">

    <link rel="stylesheet" type="text/css" href="libs/flag-icon-css/css/flag-icon.min.css">

    <link rel="stylesheet" type="text/css" href="assets/styles/pages/auth.min.css">

   <link rel="stylesheet" type="text/css" href="assets/styles/fileicons.css">

    <!-- BEGIN THEME STYLES -->

    <link rel="stylesheet" type="text/css" href="assets/styles/themes/primary.min.css">

    

    <link rel="stylesheet" href="assets/styles/timeline.css">



    <!-- END THEME STYLES -->



    <link rel="stylesheet" type="text/css" href="assets/styles/widgets/panels.min.css">

<link rel="stylesheet" type="text/css" href="assets/scripts/charts/area/area.chart.min.css">

    <link rel="stylesheet" type="text/css" href="assets/scripts/charts/radial-progress/radial-progress.chart.min.css">

    <link rel="stylesheet" type="text/css" href="assets/styles/dashboard/projects.min.css">



    <link rel="stylesheet" type="text/css" href="libs/datatables-net/media/css/dataTables.bootstrap4.min.css"> <!-- original -->

    <link rel="stylesheet" type="text/css" href="assets/styles/libs/datatables-net/datatables.min.css"> <!-- customization -->

    <link rel="stylesheet" type="text/css" href="libs/select2/css/select2.min.css"> <!-- Original -->

    <link rel="stylesheet" type="text/css" href="assets/styles/libs/select2/select2.min.css"> <!-- Customization -->

    

    <link rel="stylesheet" type="text/css" href="libs/sweetalert/sweetalert.css"> <!-- original -->

    <link rel="stylesheet" type="text/css" href="assets/styles/libs/sweetalert/sweetalert.min.css"> <!-- customization -->



    <link rel="stylesheet" type="text/css" href="libs/prism/prism.css"> <!-- original -->

    <link rel="stylesheet" type="text/css" href="assets/styles/libs/bootstrap-notify/bootstrap-notify.min.css">

<link rel="stylesheet" type="text/css" href="libs/flatpickr/flatpickr.min.css"> <!-- original -->

<link rel="stylesheet" type="text/css" href="assets/styles/libs/flatpickr/flatpickr.min.css"> 

     <!-- customization -->

    

    <style>

    .org-logo {    text-align: center;

    padding: 20px;

    padding-bottom: 0;}



    .org-logo img {max-width: 190px;  }





        .submitBtn {     float: right; position: absolute; top: 0; z-index: 9; right: 14px; top: -79px; }

        tr.edited { background-color: #000 }



        .table thead th {     font-size: 11px; padding: 8px; }

        .table td { padding: 5px; }

        .table td:nth-child(1) { font-weight: bolder; }



        div.dataTables_wrapper>.row:first-child { border: none !important; }

            

        .ks-statistics  {}



        .ks-statistics .ks-item { text-align: center; margin-bottom: 20px }

        .ks-statistics .ks-amount { font-size: 24px; font-weight: 600; }

        .ks-statistics .ks-text { font-size: 14px }

        label {font-weight: bold;}



        

        a.link {text-decoration: underline;}

        a.link:hover { text-decoration: none !important; }

        .card .row.form-group { margin-bottom: -20px; }

        .card .row.form-group:last-child { margin-bottom: 20px }



        #preloader {    position: fixed;

        width: 100%;

        height: 100%;

        overflow: hidden;

        background: url('{{ asset('assets/img/loader.gif') }}')   rgba(255, 255, 255, 0.85);

        background-repeat: no-repeat;

        background-position: center center;

        z-index: 1;

        top: 0;

        left: 0;}





        @media(max-width: 1500px)

        {

            body {

                zoom: 90%;

            }

        }



    </style>

    @stack('css')

        

</head>

<body class="ks-navbar-fixed ks-sidebar-default ks-sidebar-fixed ks-theme-primary">

    

    @include('common.header')



  

        <div class="ks-container">

        

        @include('common.sidebar')

        

        <div id="preloader"></div>

        

        @include('flash::message')

        

        @yield('pagecontent')



        </div>

   





    @yield('footer')    

    

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="infoModal">

    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <div class="modal-header">

                <h5 class="modal-title"></h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                    <span aria-hidden="true" class="fa fa-close"></span>

                </button>

            </div>

            <div class="modal-body"></div>

            <div class="modal-footer">

                <button type="button" class="btn btn-primary-outline ks-light" data-dismiss="modal">Close</button>

            </div>

        </div>

    </div>

</div>





  

<!-- BEGIN PAGE LEVEL PLUGINS -->

<script src="libs/jquery/jquery.min.js"></script>

<script src="libs/responsejs/response.min.js"></script>

<script src="libs/loading-overlay/loadingoverlay.min.js"></script>

<script src="libs/tether/js/tether.min.js"></script>

<script src="libs/bootstrap/js/bootstrap.min.js"></script>

<script src="libs/jscrollpane/jquery.jscrollpane.min.js"></script>

<script src="libs/jscrollpane/jquery.mousewheel.js"></script>

<script src="libs/flexibility/flexibility.js"></script>

<!-- END PAGE LEVEL PLUGINS -->



<!-- BEGIN THEME LAYOUT SCRIPTS -->

<script src="assets/scripts/common.js"></script>

<!-- END THEME LAYOUT SCRIPTS -->



<script src="libs/d3/d3.min.js"></script>

<script src="assets/scripts/charts/radial-progress/radial-progress.chart.js"></script>



<script src="libs/datatables-net/media/js/jquery.dataTables.min.js"></script>

<script src="libs/datatables-net/media/js/dataTables.bootstrap4.min.js"></script>

<script src="libs/select2/js/select2.min.js"></script>

<script src="libs/bootstrap-notify/bootstrap-notify.min.js"></script>

<script src="libs/sweetalert/sweetalert.min.js"></script>

<script src="libs/count-up/count-up.min.js"></script>

<script src="libs/flatpickr/flatpickr.min.js"></script>

<script src="libs/prism/prism.js"></script>



<script type="application/javascript">

(function ($) {

    $(document).ready(function() {



        $('#flash-overlay-modal').modal();



        deleteCode()



        setupAlert()



        preloader('hide');



        $('input[name="date"]').flatpickr()



          $('select').select2();





         

   

        if($(window).width() > 1200 && $(window).width() < 1600)

         $('.ks-sidebar-toggle').click();



        $('.select2').css('width','100%')



        @if(!empty(Request::get('edited')))

         highlightEdited({{ Request::get('edited') }});  

        @endif



        @if(!empty(Request::get('created')))

         highlightCreated();  

        @endif



        @if(!empty(Request::get('deleted')))

         highlightDeleted();  

        @endif



        /*ADD CLASSES TO TABLE*/

        prettifyTable();

        /*END*/



        $('input').not('input[type=button], select, input.select2-search__field').each(function () {



                var $this = $(this)

                var label = $this.closest('div.form-group').find('label').html()



                $this.attr('placeholder',label)

                

        })







        $('.datatable').DataTable();



       

    });











    function deleteCode()

    {

        $('.deleteFrm').on('submit', function () {



            var title = $(this).find('.btn-delete').attr('data-title');



            var poll = confirm("Confirm Delete "+title+" ?");



            if(poll)

            {

                return true;

            }

            else

            {

                return false;

            }



        })

    }





    $('form').on('submit', function () {



        $(this).find('input.nospaces').each(function  (index) {

                var val = $(this).val()

                $(this).val(removeSpaces(val));

        })



        $(this).find('button[type=submit]').attr('disabled','disabled')



    })



    function removeSpaces(str)

    {

        str = str.replace(/\s+/g, '');



        return str;

    }



    function prettifyTable()

    {

        $(document).find('table.table').each(function (index) {

            $(this)

                    .addClass('ks-table-info')

                    .addClass('dt-responsive')

                    .addClass('nowrap')

                    .addClass('no-footer')

                    .addClass('dtr-inline')

        })

    }



    function highlightEdited(id)

    {

        var find = $('html').find('table tbody tr[data-id='+id+']');



        if(find.length > 0)

        {

            find.addClass('alert-success');



            $.notify({ 

            title: "Success:",

            message: "Highlighted item edited successfully!"

            }, 

            {

                type: 'success-active',

                offset: {

                    x: 30,

                    y: 70

                }

            });



        }

    }



    function highlightDeleted()

    {

     

            $.notify({ 

            title: "Deleted:",

            message: "Record has been deleted successfully!"

            }, 

            {

                type: 'danger-active',

                offset: {

                    x: 30,

                    y: 70

                }

            });



    }



    function highlightCreated()

    {

     

            $.notify({ 

            title: "Success:",

            message: "Record has been created successfully!"

            }, 

            {

                type: 'success-active',

                offset: {

                    x: 30,

                    y: 70

                }

            });



    }





    function preloader(option)

    {

        if(option == 'show')

        {  

            $('#preloader').show()

         }

        else

             $('#preloader').hide()

    }



     var options = {

            useEasing : true,

            useGrouping : true,

            separator : ',',

            decimal : '.',

            prefix : '',

            suffix : ''

        };



    $('.ks-amount[data-count-up]').each(function() {

            var countUp = parseInt($(this).data('count-up'));

            (new CountUp(this, 0, countUp, 0, 2, options)).start();

        });

   

    

    $( document ).ajaxStart(function() {

        if($(document).find('.modal.show').length == 0)

            preloader('show');



        $('.btn').attr('disabled','disabled')

    });



    $( document ).ajaxComplete(function() {

         preloader('hide');



         deleteCode()

          $('.datatable').DataTable();
          prettifyTable()

         $('.btn').removeAttr('disabled')

    });



})(jQuery);

</script>

<div class="ks-mobile-overlay"></div>



    @stack('scripts')

<script>

    function viewItemIncharge(id,title)

    {

        var url = "{{ URL::route('itemIncharge') }}";



        $.post(url, {"id":id, "_token":"{{ csrf_token() }}"}, function (data) {



                 $('#infoModal .modal-title').html(title);



                $('#infoModal .modal-body').html(data);



                $('#infoModal').modal('show')



        })

    }

</script>



<script>

$.ajaxSetup({

        headers: {

            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

        }

});

$(document).on('click', 'a.delete-ajax', function(e) {

    e.preventDefault(); // does not go through with the link.



     var $this = $(this);







     swal({

            title: "Are You Sure?",

            text: "Press OK to Delete or press cancel.",

            type: "error",

            confirmButtonClass: "btn-danger",

            showCancelButton: true,

            closeOnConfirm: false,

            showLoaderOnConfirm: true



          }, function () {



               

                $.post({

                    type: $this.data('method'),

                    url: $this.attr('href')

                }).done(function (data) {

                   var success = swal({

                        title: "Deleted Successfully!",

                        text: "",

                        type: "success",

                        confirmButtonClass: "btn-success"

                      })

                    console.log(data);

                    window.location.href = data;

                });  

       

          });



    





});

</script>



<script>

    function setupAlert()

    {

        $.get("{{ URL::route('setupAlert') }}", function (data) {

            $('.setup-alert').html(data)

        })

    }



    function validateEmail(email) {

        var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

        return re.test(email);

    }

</script>

</body>

</html>

resources/views/setupalert.blade.php
@if(sizeof($data) > 0)
	
	<div class="alert alert-danger">
		<h4>Setup the following modules:</h4>
		<ul>
			@foreach($data as $alert)
				<li><b>{{ ucwords($alert['title']) }}</b> - <a href="{{ $alert['link'] }}" target="_blank">Click to Setup</a></li>
			@endforeach
		</ul>
	</div>

@endif