routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return redirect('/login'); });

 Route::get('/home', function () { return redirect()->route('home'); });


Route::group(['middleware' => ['web','auth','permission:access_panel'], 'prefix' => 'panel'], function () {

    Route::group(['middleware' => ['permission:access_admin'], 'prefix' => 'admin'], function () { 

            Route::get('home', 'AdminController@index')->name('admin.index');

    });


    Route::get('ajax/setup-alert', 'SiteController@setupAlert')->name('setupAlert');



    /*ORGANIZATION ROUTES*/

    Route::get('ajax/organization/OrganizationWithID', 'OrganizationController@OrganizationWithID')->name('OrganizationWithID');
    Route::post('ajax/organization/setOrganization', 'OrganizationController@setOrganizationViaAjax')->name('setOrganizationViaAjax');
    Route::get('organization/select', 'OrganizationController@select')->name('OrgSelect');    
 

    /*PROJECT ROUTES*/
  
    Route::get('project/select', 'ProjectController@select')->name('ProjectSelect');
    Route::get('ajax/project/ProjectWithID', 'ProjectController@ProjectWithID')->name('ProjectWithID');
    Route::post('ajax/project/setProject', 'ProjectController@setProjectViaAjax')->name('setProjectViaAjax');
    Route::get('ajax/stage/department', 'StageController@listByDepartment')->name('StageByDepartment');
    Route::get('ajax/stage/rate', 'StageController@standardRate')->name('StageStandardRate');

    Route::group(['middleware' => ['OrgProjectIfSet']],function () {
            
            /*ITEMS ROUTES*/
            Route::post('ajax/item/incharge', 'ItemController@itemIncharge')->name('itemIncharge');

            /*SUPPLIER AJAX*/

            Route::get('ajax/supplier/items', 'ItemController@supplierItems')->name('supplierItems');
            Route::get('ajax/supplier/balance', 'SupplierController@balance')->name('supplier-balance');
            Route::post('ajax/supplier/remove-item', 'ItemController@RemoveSupplierItem')->name('supplier-item-remove');
            Route::get('ajax/supplier/grn/unpaid', 'OrderGrnController@supplierGrn')->name('supplier-grn-unpaid');

            /*CONTRACTOR*/

            Route::get('ajax/contractor/department', 'ContractorController@listByDepartment')->name('ContractorByDepartment');
            Route::get('ajax/contractor/balance', 'ContractorController@balance')->name('contractor-balance');
            Route::get('ajax/contractor/unpaid-task', 'ContractorController@unpaidTask')->name('contractor-unpaid-task');

            /*OTHER ROUTES*/
            Route::get('home', 'SiteController@index')->name('home');



            /*PROJECT ROUTES*/
            Route::group(['prefix' => 'project'], function () {

                
                Route::get('product-property/list', 'ProductPropertyController@listProductProperties')->name('ProjectPropertyList');
                Route::get('product-category/list', 'ProductCategoryController@getProductCategoriesviaAjax')->name('ProductCategoriesviaAjax');
                Route::get('product-category/manage/{id}', 'ProductCategoryController@show')->name('ShowProductCategory');
                Route::post('product-category/assign', 'ProductCategoryController@assignPropertyHeader')->name('assignPropertyHeader');
                Route::post('add-product-catrgory-product', 'ProductCategoryController@AddProdToCategory')->name('AddProdToCategory');
                Route::post('delete-product-catrgory-product', 'ProductCategoryController@DeleteProdFromCategory')->name('DeleteProdFromCategory');

                Route::post('product/action', 'ProductController@action')->name('product-action');

               
                Route::resource('project-managers','ProjectManagerController');
                Route::resource('product','ProductController');
                Route::resource('product-category','ProductCategoryController');
                Route::resource('product-property/header','ProductPropertyHeaderController');
                Route::resource('product-property','ProductPropertyController');
                Route::resource('product-items','ProductItemController');
               

            });

            Route::get('order/view/{order}', 'OrderController@show')->name('view-order');
            Route::get('order/grn/prepare/{Orderid}', 'OrderController@prepareGrn')->name('prepare-grn');

            Route::get('user/login/logs','LoginLogsController@logs')->name('login-logs');
            Route::get('user/exists','UserController@checkUser')->name('user-exists');

            Route::get('inventory/items','InventoryController@items')->name('inventory-items');
            


            Route::post('payments/pay','PaymentController@pay')->name('payments-pay');

            Route::get('payments/transaction','PaymentController@viewTransaction')->name('payments-transaction');

            Route::get('payments/transaction/bank/{id}','PaymentController@bankTransaction')->name('bank-transaction');

            Route::get('payments/material-payment/create','PaymentController@materialPayment')->name('material-payment');
            Route::get('payments/contractor-payment/create','PaymentController@contractorPayment')->name('contractor-payment');
            Route::get('payments/service-payment/create','PaymentController@servicePayment')->name('service-payment');
            Route::get('payments/external-payment/create','PaymentController@externalPayment')->name('external-payment');
            Route::get('payments/external-income/create','PaymentController@externalIncome')->name('external-income');
            Route::get('payments/customer-payment/create','PaymentController@customerPayment')->name('customer-payment');

            Route::get('payments/view/{paymentid}','PaymentController@show')->name('show-payment');

            Route::get('payments/receipt/{paymentid}','PaymentController@receipt')->name('receipt');
            Route::get('payments/voucher/{paymentid}','PaymentController@voucher')->name('voucher');

            Route::any('bank-accounts/ajax','BankAccountController@ajax')->name('banks-ajax');
            Route::any('order/ajax','OrderController@ajax')->name('order-ajax');

            Route::post('change-request/update','ChangeRequestController@updateChangeRequest')->name('update-cr');
            
            Route::any('customer/products','ProductCustomerController@customerProductsCombo')->name('customer-products-combo');
            Route::any('product/cost','ProductController@cost')->name('product-cost');
            Route::any('product/upgrades','ProductController@upgrades')->name('product-upgrades');

            Route::get('reports','ReportController@index')->name('reports');
            Route::any('reports/generate','ReportController@generate')->name('report-generate');


            Route::resource('order','OrderController');
            Route::resource('ordergrn','OrderGrnController');
            Route::resource('supplier','SupplierController');
            Route::resource('contractor','ContractorController');
            Route::resource('department','DepartmentController');
            Route::resource('item','ItemController');
            Route::resource('tax','TaxController');
            Route::resource('staff','StaffController');
            Route::resource('stages','StageController');
            Route::resource('product-stages','ProductStageController');
            Route::resource('customer','CustomerController');
            Route::resource('material-transfer','MaterialTransferController');
            Route::resource('inventory','InventoryController');
            Route::resource('bank-accounts','BankAccountController');
            Route::resource('payments','PaymentController');
            Route::resource('product-customer','ProductCustomerController');
            Route::resource('change-request','ChangeRequestController');

    });

     Route::resource('organization','OrganizationController');
     Route::resource('project','ProjectController');
    


    
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use SoftDeletes;
    use \Venturecraft\Revisionable\RevisionableTrait;

    protected $dates = ['deleted_at'];
    protected $revisionCreationsEnabled = true;

	public function orders()
	{
		return $this->hasMany('App\Order','project_id');
	}

	public function products()
	{
		return $this->hasMany('App\Product','project_id');
	}

	public function customers()
    {
        return $this->hasMany('App\Customer', 'project_id');
    }
    
	public function productcategories()
	{
		return $this->hasMany('App\ProductCategory','project_id');
	}

	public function setProjCodeAttribute($value)
    {
        $this->attributes['proj_code'] = strtoupper($value);
    }

    public function setProjNameAttribute($value)
    {
        $this->attributes['proj_name'] = ucwords($value);
    }

    static public function listProjects($fields="*")
    {
       $fetch = Self::select($fields)->where('org_id', getOrganization('org_id'))->orderby('proj_name','asc')->get();

       return $fetch;
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Validator;

use Auth;

use Session;

use App\Project;

class ProjectController extends Controller
{


    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::listProjects();
        
        return view('project.list', ['projects'=>$projects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $indiaStates = getIndiaStates();

        return view('project.add',['indiaStates'=>$indiaStates]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if(empty(getOrganization('org_id'))) {
            dd("No Organization ID Set");
        }

        /*VALIDATE NEW PROJECT DATA*/

        $validator = Validator::make($request->all(), [

            'proj_code' => 'required|unique:projects',
            'proj_name' => 'required'

        ]);

        if ($validator->fails()) {
            return redirect()->route('project.create')
                        ->withErrors($validator)
                        ->withInput();
        }
   
        /*ADD NEW PROJECT DATA*/

        $Project = new Project();

        $Project->user_id = Auth::id();
        $Project->org_id = getOrganization('org_id');
        $Project->proj_code = $request->input('proj_code');
        $Project->proj_name = $request->input('proj_name');
        $Project->address_one = $request->input('proj_address_one');
        $Project->address_two = $request->input('proj_address_two');
        $Project->city = $request->input('proj_city');
        $Project->district = $request->input('proj_district');
        $Project->state = $request->input('proj_state');
        $Project->pincode = $request->input('proj_pincode');
    
        $Project->save();

        $proj_id = $Project->id;    #FETCH LAST INSERTED ID

        $this->setProject($proj_id); #SET THE CURRENT Project IN SESSION


        return redirect()->action("ProjectController@index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Project = Project::find($id);
        $indiaStates = getIndiaStates();

        return view('project.edit',['Project'=>$Project, 'indiaStates'=>$indiaStates]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Project = Project::find($id);

        $Project->address_one = $request->input('proj_address_one');
        $Project->address_two = $request->input('proj_address_two');
        $Project->city = $request->input('proj_city');
        $Project->district = $request->input('proj_district');
        $Project->state = $request->input('proj_state');
        $Project->pincode = $request->input('proj_pincode');
    
        $Project->save();

        return Redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Project::destroy($id);

        if($id == @getProject('proj_id'))
            $this->unsetProject();


        return redirect()->route('project.index', 'deleted=true');
    }

    public function select()
    {
        return view('project.select');
    }


     /*SET ORGANIZATION FUNCTIONS*/

    public function setProject($proj_id)
    {
        if($proj_id > 0)
        {
            $projFetch = Project::where('id', $proj_id)->first();

            if(isset($projFetch))
            {
                $this->unsetProject();

                $data = array("proj_id"=>$projFetch->id, "proj_code"=>$projFetch->proj_code,"proj_name"=>$projFetch->proj_name,"proj_state"=>$projFetch->state);

               session(['selectedProject' => $data]);

            }
        }
    }

    public function unsetProject()
    {
        session(['selectedProject' => ""]);
    }

    public function setProjectViaAjax(Request $request)
    {
        $proj_id = $request->input('proj_id');

        $this->setProject($proj_id);
    }

    /*ENDS SET ORGANIZATION FUNCTIONS*/

    public function getProjects($fields="*")
    {
       $fetch = Project::select($fields)->where('user_id', Auth::id())->where('org_id', getOrganization('org_id'))->orderby('proj_name','asc')->get();

       return $fetch;
    }

    public function ProjectWithID()
    {
        $data = $this->getProjects(['id','proj_name','proj_code']);

        return $data;
    }

}

resources/views/project/manager/add.blade.php
@extends('master')

@section('title','Add Project Manager')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">

             <h3>Add Project Manager <small>{{ getProject('proj_name') }}</small></h3>
              <a href="javascript:void(0)" onclick="$('#add_frm').submit()"  class="btn btn-success pull-right">Add New</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">

						@include('common.pagetop')
						
   {{ Form::open(['route' => 'register', 'id'=>'add_frm']) }}
						<div class="row">
							<div class="col-md-6">
								<div class="card">
									
		                        <div class="card-block">
		                     
		                            <h5 class="card-title">Personal Details</h5>
		                            	<div class="form-group row">
		                                    <label for="role_title" class="col-sm-2 form-control-label">Role</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::select('role_title', ['Project Manager'=>'Project Manager','Project Co-ordinator'=>'Project Co-ordinator'], null, ['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                            
		                            	 <div class="form-group row">
		                                    <label for="name" class="col-sm-2 form-control-label">Name</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('name','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                                 <div class="form-group row">
		                                    <label for="phone" class="col-sm-2 form-control-label">Phone</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('phone','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                              
		                                
		                                 <div class="form-group row">
		                                    <label for="address" class="col-sm-2 form-control-label">Address</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('address','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>


		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">District</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('district','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="state" class="col-sm-2 form-control-label">State</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::select('state', $indiaStates, null, ['placeholder' => 'Select a state','class'=>'form-control']) }}
		                                    </div>
		                                </div>
										
										<br>
										

		                                <input type="hidden" name="projectmanager" value="true">
										<input type="hidden" name="redir" value="{{ URL::route('project-managers.index') }}">
		                     
		                        </div>
		                
								</div>
							</div>
							<div class="col-md-6">
								
								<div class="card">
									<div class="card-block">
										
   <h5 class="card-title">Login Details</h5>
		
         

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                    
                    
								
							
									</div>
								</div>
							</div>
						</div>
						   {{ Form::close() }}

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection

resources/views/project/manager/edit.blade.php
@extends('master')

@section('title','Edit Project Manager')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">

             <h3>Edit Project Manager <small>{{ $User->user->name }}</small></h3>
              <a href="javascript:void(0)" onclick="$('#add_frm').submit()"  class="btn btn-success pull-right">Update</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">

						@include('common.pagetop')
						
   {{ Form::open(['action' => ['ProjectManagerController@update',$User->user_id], 'id'=>'add_frm','method'=>'PUT']) }}
						<div class="row">
							<div class="col-md-6">
								<div class="card">
									
		                        <div class="card-block">
		                     
		                            <h5 class="card-title">Personal Details</h5>
		                            	
		                            
		                            	 <div class="form-group row">
		                                    <label for="name" class="col-sm-2 form-control-label">Name</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('name', $User->user->name, ['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                                 <div class="form-group row">
		                                    <label for="phone" class="col-sm-2 form-control-label">Phone</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('phone', $User->user->detail->phone,['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                              
		                                
		                                 <div class="form-group row">
		                                    <label for="address" class="col-sm-2 form-control-label">Address</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('address', $User->user->detail->address,['class'=>'form-control']) }}
		                                    </div>
		                                </div>


		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">District</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('district', $User->user->detail->district,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                   <div class="form-group row">
		                                    <label for="state" class="col-sm-2 form-control-label">State</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::select('state', getindiaStates(), $User->user->detail->state, ['placeholder' => 'Select a state','class'=>'form-control']) }}
		                                    </div>
		                                </div>

										<div class="form-group row">
		                                    <label for="role_title" class="col-sm-2 form-control-label">State</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::select('role_title', ['Project Manager'=>'Project Manager','Project Co-ordinator'=>'Project Co-ordinator'],  $User->user->detail->role_title, ['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <input type="hidden" name="projectmanager" value="true">
										<input type="hidden" name="redir" value="{{ URL::route('project-managers.index') }}">
		                     
		                        </div>
		                
								</div>
							</div>
							<div class="col-md-6">
								
								<div class="card">
									<div class="card-block">
										
   <h5 class="card-title">Login Details</h5>
		
         

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="control-label">E-Mail Address: </label> {{ $User->user->email }}

                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="control-label">New Password:</label>

                                Click <b>Forgot Password</b> at Login page.
                        </div>

                        
                    
                    
								
							
									</div>
								</div>
							</div>
						</div>
						   {{ Form::close() }}

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection

resources/views/project/manager/list.blade.php
@extends('master')

@section('title','List Project Roles Users')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">
              <h3>List Project Roles Users: <small>{{ getProject('proj_name') }}</small></h3>
              <a href="{{ URL::Action('ProjectManagerController@create') }}"  class="btn btn-success pull-right">Add New</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						
						<div class="card">
		                        <div class="card-block">
		                            <h5 class="card-title">You have {{ $ProjectManagers->count() }} project manager added to this project</h5>
									
									@if($ProjectManagers->count() > 0)

										<table class="table datatable table-condensed table-bordered table-hover">
											<thead>
												<tr>
													<th width="220">Name</th>
													<th>Phone</th>
													<th>Email</th>
													<th>District</th>
													<th>State</th>
													
													<th>Options</th>
												</tr>
											</thead>

											<tbody>
												@foreach($ProjectManagers as $manager)
													<tr>
														<td><strong><a href="{{ URL::action('ProjectManagerController@show', $manager->user->id)  }}">{{ $manager->user->name }}</a></strong></td>
														<td>{{ @$manager->user->detail->phone }}</td>
														<td>{{ $manager->user->email }}</td>
														<td>{{ @$manager->user->detail->district }}</td>
														<td>{{ @$manager->user->detail->state }}</td>
														<td>{!! deleteEditModelBtn("project-managers",$manager->user->id, $manager->user->name) !!}</td>
													</tr>
												@endforeach
											</tbody>

										</table>

									@else
										No Project Managers Added!
									@endif
		                        </div>
		                </div>

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection

resources/views/project/manager/view.blade.php
@extends('master')

@section('title','Project Manager Details')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">

                <h3>{{ $User->user->name }} <small>Project Manager Details</small> </h3>
              
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						
						@include('common.pagetop')
						
						<div class="row">
							<div class="col-lg-12">

						<!-- ORGANIZATION NAME BLOCK -->
							<div class="card">
		                        <div class="card-block">
		                        	<h5 class="card-title">Login Stamps</h5>

		                        	<table class="table" id="loginLogs">

		                        		<thead>
		                        			<tr>
		                        				<th>#</th>
		                        				<th>Event</th>
		                        				<th>IP Address</th>
		                        				<th>Timestamp</th>
		                        			</tr>
		                        		</thead>
		                        		
		                        	</table>
		                        </div>
		                    </div>

		                    <!-- END ORGANIZATION NAME BLOCK -->

			            </div>

			            <div class="col-lg-6">
			            	
			            </div>
						</div>

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection

@push('scripts')

	<script>
		$(function() {
		    $('#loginLogs').DataTable({
		        processing: true,
		        serverSide: true,
		        ajax: '{!! route('login-logs') !!}?user_id={{ $User->user->id }}',
		        columns: [
		            { data: 'id', name: 'id' },
		            { data: 'event', name: 'event' },
		            { data: 'ip_address', name: 'ip_address' },
		            { data: 'created_at', name: 'timestamp' }
		        ]
		    });
		});
</script>

@endpush