routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return redirect('/login'); });

 Route::get('/home', function () { return redirect()->route('home'); });


Route::group(['middleware' => ['web','auth','permission:access_panel'], 'prefix' => 'panel'], function () {

    Route::group(['middleware' => ['permission:access_admin'], 'prefix' => 'admin'], function () { 

            Route::get('home', 'AdminController@index')->name('admin.index');

    });


    Route::get('ajax/setup-alert', 'SiteController@setupAlert')->name('setupAlert');



    /*ORGANIZATION ROUTES*/

    Route::get('ajax/organization/OrganizationWithID', 'OrganizationController@OrganizationWithID')->name('OrganizationWithID');
    Route::post('ajax/organization/setOrganization', 'OrganizationController@setOrganizationViaAjax')->name('setOrganizationViaAjax');
    Route::get('organization/select', 'OrganizationController@select')->name('OrgSelect');    
 

    /*PROJECT ROUTES*/
  
    Route::get('project/select', 'ProjectController@select')->name('ProjectSelect');
    Route::get('ajax/project/ProjectWithID', 'ProjectController@ProjectWithID')->name('ProjectWithID');
    Route::post('ajax/project/setProject', 'ProjectController@setProjectViaAjax')->name('setProjectViaAjax');
    Route::get('ajax/stage/department', 'StageController@listByDepartment')->name('StageByDepartment');
    Route::get('ajax/stage/rate', 'StageController@standardRate')->name('StageStandardRate');

    Route::group(['middleware' => ['OrgProjectIfSet']],function () {
            
            /*ITEMS ROUTES*/
            Route::post('ajax/item/incharge', 'ItemController@itemIncharge')->name('itemIncharge');

            /*SUPPLIER AJAX*/

            Route::get('ajax/supplier/items', 'ItemController@supplierItems')->name('supplierItems');
            Route::get('ajax/supplier/balance', 'SupplierController@balance')->name('supplier-balance');
            Route::post('ajax/supplier/remove-item', 'ItemController@RemoveSupplierItem')->name('supplier-item-remove');
            Route::get('ajax/supplier/grn/unpaid', 'OrderGrnController@supplierGrn')->name('supplier-grn-unpaid');

            /*CONTRACTOR*/

            Route::get('ajax/contractor/department', 'ContractorController@listByDepartment')->name('ContractorByDepartment');
            Route::get('ajax/contractor/balance', 'ContractorController@balance')->name('contractor-balance');
            Route::get('ajax/contractor/unpaid-task', 'ContractorController@unpaidTask')->name('contractor-unpaid-task');

            /*OTHER ROUTES*/
            Route::get('home', 'SiteController@index')->name('home');



            /*PROJECT ROUTES*/
            Route::group(['prefix' => 'project'], function () {

                
                Route::get('product-property/list', 'ProductPropertyController@listProductProperties')->name('ProjectPropertyList');
                Route::get('product-category/list', 'ProductCategoryController@getProductCategoriesviaAjax')->name('ProductCategoriesviaAjax');
                Route::get('product-category/manage/{id}', 'ProductCategoryController@show')->name('ShowProductCategory');
                Route::post('product-category/assign', 'ProductCategoryController@assignPropertyHeader')->name('assignPropertyHeader');
                Route::post('add-product-catrgory-product', 'ProductCategoryController@AddProdToCategory')->name('AddProdToCategory');
                Route::post('delete-product-catrgory-product', 'ProductCategoryController@DeleteProdFromCategory')->name('DeleteProdFromCategory');

                Route::post('product/action', 'ProductController@action')->name('product-action');

               
                Route::resource('project-managers','ProjectManagerController');
                Route::resource('product','ProductController');
                Route::resource('product-category','ProductCategoryController');
                Route::resource('product-property/header','ProductPropertyHeaderController');
                Route::resource('product-property','ProductPropertyController');
                Route::resource('product-items','ProductItemController');
               

            });

            Route::get('order/view/{order}', 'OrderController@show')->name('view-order');
            Route::get('order/grn/prepare/{Orderid}', 'OrderController@prepareGrn')->name('prepare-grn');

            Route::get('user/login/logs','LoginLogsController@logs')->name('login-logs');
            Route::get('user/exists','UserController@checkUser')->name('user-exists');

            Route::get('inventory/items','InventoryController@items')->name('inventory-items');
            


            Route::post('payments/pay','PaymentController@pay')->name('payments-pay');

            Route::get('payments/transaction','PaymentController@viewTransaction')->name('payments-transaction');

            Route::get('payments/transaction/bank/{id}','PaymentController@bankTransaction')->name('bank-transaction');

            Route::get('payments/material-payment/create','PaymentController@materialPayment')->name('material-payment');
            Route::get('payments/contractor-payment/create','PaymentController@contractorPayment')->name('contractor-payment');
            Route::get('payments/service-payment/create','PaymentController@servicePayment')->name('service-payment');
            Route::get('payments/external-payment/create','PaymentController@externalPayment')->name('external-payment');
            Route::get('payments/external-income/create','PaymentController@externalIncome')->name('external-income');
            Route::get('payments/customer-payment/create','PaymentController@customerPayment')->name('customer-payment');

            Route::get('payments/view/{paymentid}','PaymentController@show')->name('show-payment');

            Route::get('payments/receipt/{paymentid}','PaymentController@receipt')->name('receipt');
            Route::get('payments/voucher/{paymentid}','PaymentController@voucher')->name('voucher');

            Route::any('bank-accounts/ajax','BankAccountController@ajax')->name('banks-ajax');
            Route::any('order/ajax','OrderController@ajax')->name('order-ajax');

            Route::post('change-request/update','ChangeRequestController@updateChangeRequest')->name('update-cr');
            
            Route::any('customer/products','ProductCustomerController@customerProductsCombo')->name('customer-products-combo');
            Route::any('product/cost','ProductController@cost')->name('product-cost');
            Route::any('product/upgrades','ProductController@upgrades')->name('product-upgrades');

            Route::get('reports','ReportController@index')->name('reports');
            Route::any('reports/generate','ReportController@generate')->name('report-generate');


            Route::resource('order','OrderController');
            Route::resource('ordergrn','OrderGrnController');
            Route::resource('supplier','SupplierController');
            Route::resource('contractor','ContractorController');
            Route::resource('department','DepartmentController');
            Route::resource('item','ItemController');
            Route::resource('tax','TaxController');
            Route::resource('staff','StaffController');
            Route::resource('stages','StageController');
            Route::resource('product-stages','ProductStageController');
            Route::resource('customer','CustomerController');
            Route::resource('material-transfer','MaterialTransferController');
            Route::resource('inventory','InventoryController');
            Route::resource('bank-accounts','BankAccountController');
            Route::resource('payments','PaymentController');
            Route::resource('product-customer','ProductCustomerController');
            Route::resource('change-request','ChangeRequestController');

    });

     Route::resource('organization','OrganizationController');
     Route::resource('project','ProjectController');
    


    
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class Customer extends Model
{
    use \Venturecraft\Revisionable\RevisionableTrait;
    
    protected $revisionCreationsEnabled = true;
    
    use SoftDeletes;

    public function getNameAttribute($value)
    {
    	return ucwords($value);
    }

   static public function scopeofProject($query,$project_id="")
   {
      $project_id = (!empty($project_id) ? $project_id : getProject('proj_id'));

      return $query->where('project_id',$project_id);
   }

    static public function scopeofOrg($query,$org_id="")
    {
      $org_id = (!empty($org_id) ? $org_id : getOrganization('org_id'));

      return $query->where('org_id',$org_id);
    }

   public function products()
    {
    	return $this->hasMany('App\ProductCustomer','customer_id');
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Auth;
use Session;
use Datatables;

use App\Customer;

use App\Product;
use App\ChangeRequest;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $org_id = getOrganization('org_id');
        $Customers = Customer::where('org_id', $org_id)->orderBy('name')->get();
        return view('customer.list', ['Customers'=>$Customers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
       $Customer = Customer::ofProject()->findOrFail($id);
       $Products = Product::availableProducts();
       $ChangeRequests = ChangeRequest::where('user_id', $id)->get();
       
       return view('customer.view', compact('Customer', 'Products','ChangeRequests'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Customer = Customer::ofProject()->find($id);

        return view('customer.edit', compact('Customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $validator = Validator::make($request->all(), [

            'name' => 'required',
            'email' => 'required',
            'phone' => 'required'
        
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $Customer = Customer::find($id);

        $Customer->name     =   $request->input('name');
        $Customer->email     =   $request->input('email_primary');
        $Customer->phone     =   $request->input('phone');
        $Customer->city     =   $request->input('city');
        $Customer->state     =   $request->input('state');
        $Customer->name_sec     =   $request->input('name_sec');
        $Customer->phone_sec     =   $request->input('phone_sec');
        $Customer->email_sec     =   $request->input('email_sec');

        $Customer->save();

        return redirect()->back();


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/add.blade.php
@extends('master')

@section('title','Add Customer')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">

             <h3>Add Customer <small>{{ getProject('proj_name') }}</small></h3>
              <a href="javascript:void(0)" onclick="$('#add_frm').submit()"  class="btn btn-success pull-right">Add New</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">

						@include('common.pagetop')
						
   {{ Form::open(['route' => 'register', 'id'=>'add_frm']) }}
						<div class="row">
							<div class="col-md-6">
								<div class="card">
									
		                        <div class="card-block">
		                     
		                            <h5 class="card-title">Personal Details</h5>

		                            	<div class="form-group row">
		                                    <label for="name" class="col-sm-2 form-control-label">Name</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('name','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Email</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::email('email_primary','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                                <div class="form-group row">
		                                    <label for="phone" class="col-sm-2 form-control-label">Phone</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('phone','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                              
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">District</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('city','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="state" class="col-sm-2 form-control-label">State</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::select('state', getIndiaStates(), null, ['placeholder' => 'Select a state','class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Secondary Name</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('name_sec','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Secondary Phone</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('phone_sec','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Secondary Email</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::email('email_sec','',['class'=>'form-control']) }}
		                                    </div>
		                                </div>

										<input type="hidden" name="customer" value="true">
										<input type="hidden" name="redir" value="{{ URL::route('customer.index') }}">
		                     
		                        </div>
		                
								</div>
							</div>
							<div class="col-md-6">
								
								<div class="card">
									<div class="card-block">
										
   <h5 class="card-title">Login Details</h5>


                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" onblur="checkCustomer()" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="password_fields">

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>
					
                    		<p>Note: Customer login is created only one time</p>

         				</div>

         					<p class="message"></p>
                    
								
							
									</div>
								</div>
							</div>
						</div>
						   {{ Form::close() }}

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection


@push('scripts')

	<script>
		
		function checkCustomer()
		{
			var email = $('#email').val();

			var message = "";

			if(email != '')
			{
				if(validateEmail(email))
				{

					$.getJSON('{{ route('user-exists') }}', {'email':email, 'type':'customer'}, function (json){

						var status = $.trim(json.status);

						if(status == 'exists')
						{
							message = "Customer login details found as <b>"+json.customer.name+"</b> ! Customer will be added under this login account.";

							$('.password_fields').hide();


						}
						else if(status == 'locked')
						{
							message = "Cannot use this email for login. Please enter a new email.";

							$('.password_fields').show();
						}
						else
							$('.password_fields').show();

						$('.message').html(message)

					})
					
				}
			}
		}

	</script>

@endpush

resources/views/customer/edit.blade.php
@extends('master')

@section('title','Edit Customer')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">

             <h3>Edit Customer <small>{{ getProject('proj_name') }}</small></h3>
              <a href="javascript:void(0)" onclick="$('#add_frm').submit()"  class="btn btn-primary pull-right">Submit</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">

						@include('common.pagetop')
						
   {{ Form::model($Customer, ['route' => ['customer.update', $Customer->id], 'method' => 'PUT', 'id'=>'add_frm']) }}
						<div class="row">
							<div class="col-md-6">
								<div class="card">
									
		                        <div class="card-block">
		                     
		                            <h5 class="card-title">Personal Details</h5>

		                            	<div class="form-group row">
		                                    <label for="name" class="col-sm-2 form-control-label">Name</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('name',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Email</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::email('email',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                                <div class="form-group row">
		                                    <label for="phone" class="col-sm-2 form-control-label">Phone</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('phone',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>	

		                              
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">District</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('city',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

		                                <div class="form-group row">
		                                    <label for="state" class="col-sm-2 form-control-label">State</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::select('state', getIndiaStates(), null, ['placeholder' => 'Select a state','class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Secondary Name</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('name_sec',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Secondary Phone</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::text('phone_sec',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>
		                                 <div class="form-group row">
		                                    <label for="district" class="col-sm-2 form-control-label">Secondary Email</label>
		                                    <div class="col-sm-10">
		                                       	{{ Form::email('email_sec',null,['class'=>'form-control']) }}
		                                    </div>
		                                </div>

										<input type="hidden" name="customer" value="true">
										<input type="hidden" name="redir" value="{{ URL::route('customer.index') }}">
		                     
		                        </div>
		                
								</div>
							</div>
							
						</div>
						   {{ Form::close() }}

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection


@push('scripts')

	<script>
		
		function checkUser(e)
		{
			/*var email = $(e).val();

			if(email != '')
			{
				$.get('{{ route('user-exists') }}', {'email':email}. function (data){



				})
			}*/
		}

	</script>

@endpush

resources/views/customer/list.blade.php
@extends('master')

@section('title','List Customers')

@section('pagecontent')

  <div class="ks-column ks-page">
        <div class="ks-header">

            <section class="ks-title">
              <h3>Project Customers <small>{{ getProject('proj_name') }}</small></h3>
              <a href="{{ URL::Action('CustomerController@create') }}"  class="btn btn-success pull-right">Add New</a>
            </section>
        </div>

		<div class="ks-content">
            <div class="ks-body">
				
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						
						<div class="card">
		                        <div class="card-block">
		                            <h5 class="card-title">You have {{ $Customers->count() }} customers added to this project</h5>
									
									@if($Customers->count() > 0)

										<table class="table datatable">
											<thead>
												<tr>
													<th>Customer Name</th>
													<th>Phone</th>
													<th>Email</th>
													<th>City</th>
													<th>State</th>
													<th>Options</th>
												</tr>
											</thead>

											<tbody>
												@foreach($Customers as $Customer)

													<tr>
														<td><a href="{{ route('customer.show',$Customer->id) }}">{{ $Customer->name }}</a></td>
														<td>{{ $Customer->phone }}</td>
														<td>{{ $Customer->email }}</td>
														<td>{{ $Customer->city }}</td>
														<td>{{ $Customer->state }}</td>
														<td>{!! deleteEditModelBtn("customer",$Customer->id, $Customer->name) !!}</td>
													</tr>

												@endforeach
											</tbody>

										</table>

									@else
										No Project Managers Added!
									@endif
		                        </div>
		                </div>

					</div>
						
			     </div>

			            
		        </div>

   </div>
	</div>
				</div>
@endsection